import Head from "next/head";
import { Hero } from "../components/Hero";
import { Infosection } from "../components/Infosection";
import { Instagram } from "../components/Instagram";
import { Navbar } from "../components/Navbar";
import Promotion from "../components/Promotion";
import { HomeGallery } from "../components/Services";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Phils Creations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Infosection />
      <HomeGallery />
      <Promotion />
      <Instagram />
    </div>
  );
}
